### ISSUE TITLE
功能请求:在人物名字中添加对应主页的链接

### ISSUE THREAD

**Issue by mingyEx** [calee0219/leetcode-following#3]
![image](https://github.com/calee0219/leetcode-following/assets/40135358/8ede9783-58a1-4f3b-a975-e36b9d3d058b)
比如这里，如果点击人物名字可以到达对应的人物主页，会很方便，因为“通过问题数量”包含的信息量太少。、
否则想要进入该人物的主页我们就得“打开新的页面，找到自己的主页，将名字替换为该好友的名字”，这样的操作不如点一下方便。

**Comment by calee0219** [comment]
That's a really good idea! Thank you for your feedback and I'll try to implement it. :D

**Comment by mingyEx** [comment]
Perhaps there are more things we can do, such as associating this project with github, so that users need github account authorization to use it, so that the text information of `leetcode-following` can be saved permanently, either on a third-party server or in a file that is automatically generated after the user forks some repo. and make some automated changes.

Moreover, we can extend this feature to sites without built-in social systems such as codeforces.
I don't have any experience with this, so I don't know how difficult this task is, but it just came to me in a flash.
